# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastra.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cadastrar(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(626, 486)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 80, 261, 31))
        self.label.setStyleSheet("font: 14pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 170, 47, 13))
        self.label_2.setObjectName("label_2")
        self.edtCodigo = QtWidgets.QLineEdit(Dialog)
        self.edtCodigo.setGeometry(QtCore.QRect(160, 170, 261, 20))
        self.edtCodigo.setObjectName("edtCodigo")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 220, 47, 13))
        self.label_3.setObjectName("label_3")
        self.edtNome = QtWidgets.QLineEdit(Dialog)
        self.edtNome.setGeometry(QtCore.QRect(160, 220, 261, 20))
        self.edtNome.setObjectName("edtNome")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(90, 260, 47, 13))
        self.label_4.setObjectName("label_4")
        self.edtFuncao = QtWidgets.QLineEdit(Dialog)
        self.edtFuncao.setGeometry(QtCore.QRect(160, 260, 271, 20))
        self.edtFuncao.setObjectName("edtFuncao")
        self.butCadastrar = QtWidgets.QPushButton(Dialog)
        self.butCadastrar.setGeometry(QtCore.QRect(120, 330, 75, 23))
        self.butCadastrar.setObjectName("butCadastrar")
        self.butCancelar = QtWidgets.QPushButton(Dialog)
        self.butCancelar.setGeometry(QtCore.QRect(240, 330, 75, 23))
        self.butCancelar.setObjectName("butCancelar")
        self.butLimpar = QtWidgets.QPushButton(Dialog)
        self.butLimpar.setGeometry(QtCore.QRect(360, 330, 75, 23))
        self.butLimpar.setObjectName("butLimpar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Cadastrar Funcionario"))
        self.label_2.setText(_translate("Dialog", "Codigo"))
        self.label_3.setText(_translate("Dialog", "Nome"))
        self.label_4.setText(_translate("Dialog", "Funcao"))
        self.butCadastrar.setText(_translate("Dialog", "Cadastrar"))
        self.butCancelar.setText(_translate("Dialog", "Cancelar"))
        self.butLimpar.setText(_translate("Dialog", "Limpar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Cadastrar()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
