# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabela.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tabela(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(506, 332)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(80, 30, 256, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 506, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivos = QtWidgets.QMenu(self.menubar)
        self.menuArquivos.setObjectName("menuArquivos")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionCadastra = QtWidgets.QAction(MainWindow)
        self.actionCadastra.setObjectName("actionCadastra")
        self.actionexcluir = QtWidgets.QAction(MainWindow)
        self.actionexcluir.setObjectName("actionexcluir")
        self.actionlistar = QtWidgets.QAction(MainWindow)
        self.actionlistar.setObjectName("actionlistar")
        self.menuArquivos.addAction(self.actionCadastra)
        self.menuArquivos.addAction(self.actionexcluir)
        self.menuArquivos.addAction(self.actionlistar)
        self.menubar.addAction(self.menuArquivos.menuAction())
        self.toolBar.addAction(self.actionCadastra)
        self.toolBar.addAction(self.actionexcluir)
        self.toolBar.addAction(self.actionlistar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Codigo"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome"))
        self.menuArquivos.setTitle(_translate("MainWindow", "Arquivos"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionCadastra.setText(_translate("MainWindow", "Cadastra"))
        self.actionexcluir.setText(_translate("MainWindow", "excluir"))
        self.actionlistar.setText(_translate("MainWindow", "listar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Tabela()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
